[package]
name = "LearningWASM"
version = "0.1.0"
authors = ["Satindra Ramalingam <satindra.r@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"